### ISSUE TITLE
Regenerate README images, handle changes figure captions/alts behaviour.

### ISSUE THREAD

**Issue by Fgazzelloni** [trevorld/ggpattern#110]
**Bug description**

Vignette - Quickstart section plot title misspelled: ggpattern::geom_pattern_col()<https://coolbutuseless.github.io/package/ggpattern/>

**Comment by trevorld** [comment]
* Looks like the typo is already fixed in `README.Rmd`, just need to re-generate imagge
* However it looks like `{knitr}` now inserts some "plot of chunk unnamed-chunk-2" text in the output which we may want to suppress or alternatively come up with a better figure caption and/or figure alt.
