### ISSUE TITLE
Remove or warn about unreliable "placeholder" pattern examples in vignettes?

### ISSUE THREAD

**Issue by Yann-C-INN** [trevorld/ggpattern#111]
I get this error:
```
Error in `value[[3L]]()`:
! img_read() non-specific error with magick::image_read("https://placekitten.com/97/36")
ℹ HTTP error 522.
```
When running the code from here [ggpattern](https://coolbutuseless.github.io/package/ggpattern/articles/geom-gallery-array.html#geom-density-pattern-)
Specifically, this code chunck:
```
library(magick)
library(ggpattern)
ggplot(mpg, aes(class)) +
  geom_bar_pattern(
    aes(
      pattern_angle = class
    ), 
    pattern         = 'placeholder',
    pattern_type    = 'kitten',
    fill            = 'white', 
    colour          = 'black',
    pattern_spacing = 0.025
  ) +
  theme_bw(18) +
  labs(
    title = "ggpattern::geom_bar_pattern()",
    subtitle = "pattern = 'placeholder', pattern_type = 'kitten'"
  ) + 
  theme(legend.position = 'none') +
  coord_fixed(ratio = 1/15) + 
  scale_pattern_discrete(guide = guide_legend(nrow = 1))
```
ggpattern_1.0.1 
ggplot2_3.5.0   

platform       x86_64-w64-mingw32               
arch           x86_64                           
os             mingw32                          
crt            ucrt                             
system         x86_64, mingw32                  
status                                          
major          4                                
minor          3.2                              
year           2023                             
month          10                               
day            31                               
svn rev        85441                            
language       R                                
version.string R version 4.3.2 (2023-10-31 ucrt)
nickname       Eye Holes

**Comment by trevorld** [comment]
* This reproduces for me right now.
* https://placekitten.com seems to be up but really slow right now.  
* This error may go away if that service gets faster later.

**Comment by trevorld** [comment]
Perhaps we should remove the more fragile "placeholder" examples from the vignettes?

**Comment by trevorld** [comment]
* Those "kitten" placeholder examples still not working for me.
* I've removed those examples from the vignettes:

  + One was replaced with a "plasma" pattern example
  + One was simply removed

* The website isn't completely down so there is still hope it might work again later so probably shouldn't remove it outright.
* We may want to change the default away from "kitten" to another placeholder pattern
