### ISSUE TITLE
Geom_fruit

### ISSUE THREAD

**Issue by AThivolle** [trevorld/ggpattern#126]
Hello Trevor, 

Your tool is really nice!
I need to plot a tree and  tiles/heatmap next to it, so I use geom_fruit.
Would it be possible to include this feature? 

Best,

Alix

**Comment by trevorld** [comment]
What feature exactly do you want?  Can't you already pass `{ggpattern}` geoms to the `geom` argument of `ggtreeExtra::geom_fruit()`?

**Comment by AThivolle** [comment]
Sorry I didn't think about it.. 
It works now. 
Thanks
